# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
      time: "05:00"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
      - "asgrim"
      - "jaydiablo"
    labels:
      - "dependencies"
    versioning-strategy: "increase-if-necessary"
    ignore:
      - dependency-name: "browscap/browscap-php"
        versions:
          - ">= 0"
      - dependency-name: "ergebnis/json-normalizer"
        versions:
          - ">= 0"
      - dependency-name: "monolog/monolog"
        versions:
          - ">= 0"
      - dependency-name: "phpunit/phpunit"
        versions:
          - ">= 0"
      - dependency-name: "symfony/cache"
        versions:
          - ">= 0"
      - dependency-name: "symfony/console"
        versions:
          - ">= 0"
      - dependency-name: "symfony/finder"
        versions:
          - ">= 0"
      - dependency-name: "twig/twig"
        versions:
          - ">= 0"
    commit-message:
      include: "scope"
      prefix: "Build"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "05:00"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
      - "asgrim"
      - "jaydiablo"
    labels:
      - "dependencies"
    commit-message:
      prefix: "github-actions"
